### ISSUE TITLE
[BUG/FE] 환자 차트 상세 조회에 관하여

### ISSUE THREAD

**Issue by osohyun0224** [sync-without-async/Rehab-FrontEnd#57]
### Describe the bug
- 환자의 상세 차트 정보를 가져오지 못하는 연결 이슈 발생

### To Reproduce
[1] ```DoctorDetailChart```
- 환자의 상세 차트에서 DoctorDetailChart를 포함 다른 요소들도 api 연결 중입니다.
- 처음에는 cno로 환자 상세 정보를 불러오도록 조회한다고 생각해 getbyStaff 로 구현 시도 했으나 실패하였습니다.
- 제가 외래 진료 추가  api 연결할때 mid로 연결했어서 mid로 해보자하고 getbyPatient 로 구현 시도했으나  .... 눈물만
- 암튼 mid로 해보고 개발자도구에서 확인을 하니까.... 
![image](https://github.com/sync-without-async/Rehab-FrontEnd/assets/53892427/a974e3fe-07ff-464d-845b-05832484e745)

[2] ```DoctorDetailHeader```
- 환자의 이름 / 생년월일 / 성별 / 나이 정보가 담긴 헤더 컴포넌트의 api 연결 중입니다.
- [1]에서 구현한 getbyPatient함수로 연결해두었는데 [1]이랑 동일한 오류발생으로 환자의 상세 정보를 가져오지 못합니다

[논외]
- example_id에 대한 정보를 아예 가져오지 못하고 있습니다
- 아직 환자 상세 차트 정보에 "최근 외래 진료일" 데이터 정보 없어서 백엔드에게 해달라고 했는데 아직 명세에 안 적혀있어요 일단 최근 외래 진료일 제외하고 나머지 진행하였습니다.
![image](https://github.com/sync-without-async/Rehab-FrontEnd/assets/53892427/2fad12dd-66ae-4d43-9e82-315b7c04b51c)

**Comment by PortalCube** [comment]
> [1] DoctorDetailChart, [2] DoctorDetailHeader

각 컴포넌트에서 API를 따로 불러오지 않도록 수정하고 ChartDetail 페이지에서 한번만 API 호출시키고 Reducer 패턴으로 해당 API의 데이터가 필요한 다른 컴포넌트에서 손쉽게 공유할 수 있도록 수정했습니다.

해당 컴포넌트에서 환자의 id 값을 제대로 못 불러오는 문제가 있었어서, 해당 부분 수정하여 메인 API 호출 부분에 적용하여 수정 완료했습니다.

> example_id에 대한 정보를 아예 가져오지 못하고 있습니다

example_id는 그냥 페이지 만들때 임시로 박아둔거였고... 아마 DB에 해당 계정이 없어서 못불러왔을거에요!


> 아직 환자 상세 차트 정보에 "최근 외래 진료일" 데이터 정보 없어서 백엔드에게 해달라고 했는데 아직 명세에 안 적혀있어요 일단 최근 외래 진료일 제외하고 나머지 진행하였습니다.

최근 외래 진료일은 medicalRecords에서 가장 최근 데이터 하나 뽑아온 다음, 해당 데이터의 schedule 값을 불러오면 됩니다.

다만 다음 외래 진료일 필드는 없어서 백엔드에 요청해보겠습니다..
